### PR TITLE
mark documents as started and discard started ones, closes #18

### LINKED ISSUE #18: Prevent double notifications in any case
Due to the dynamics of the deployment process, we risk to notify twice even big amount of change events. See #17 for more details. A simple solution in order to avoid double notifications is suggested by @jo in a [comment to that issue](https://github.com/eHealthAfrica/sense-dispatch/issues/17#issuecomment-138866756). Keeping track of the possible stages of processing and possible failures can be considered as an improvements, also considering that processing is monitored via Sentry and every error will be notified that way. For the moment we can avoid sending duplicate messages by storing a property `dispatcherNotification` with value `"started"` _before_ any notification occurs. The Couch view needs to be modified in order to exclude documents with `dispatcherNotification` set

### PR DESCRIPTION
**Pull request by danse**
again, @jo or/and @skoni :grin:

### CODE REVIEW

**Comment by danse** [comment]
alright i will look how to fix the tests

**Comment by danse** [comment]
Hum this is a weird issue https://github.com/pouchdb/pouchdb/issues/4301

**Comment by danse** [comment]
Whoohoo, tests finally pass! :tada: 

:sweat:

**Comment by jo** [comment]
:rocket:

**Comment by tillre** [comment]
This writes and checks the `started` state. It would also be of value to persist the outcome of the message sending, either a success or an error by setting the state accordingly. But this is probably outside of the scope of this PR.

**Comment by tillre** [comment]
LGTM

**Comment by danse** [comment]
Yep i did the minimum in order to deploy as soon as possible. We could always extend this in the future

**Pull request merged**
